# -*- coding: utf-8 -*-
"""ai_studio_code (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVA7QaQI3ry20M3pP9ZWhKLfMuUk0b-W

# Projeto Prático: Fine-Tuning de IA Visual para OCR de Fórmulas Matemáticas (LaTeX)

**Objetivo da Atividade:** Realizar o ajuste fino (fine-tuning) de um modelo de linguagem visual (VLM) pré-treinado para extrair equações de imagens e formatá-las em código LaTeX sintaticamente correto.

**Abordagem Metodológica:**
- **Modelo Base:** Utilização do `Qwen3.5-0.8B-Vision` devido à sua eficiência computacional e arquitetura multimodal.
- **Otimização:** Aplicação de LoRA (Low-Rank Adaptation) em camadas de atenção e MLP para reduzir o custo computacional (VRAM), treinando apenas os parâmetros mais relevantes.
- **Framework de Treinamento:** Uso de bibliotecas de otimização de hardware (Triton, bitsandbytes, flash-linear-attention).

## 1. Configuração do Ambiente
Instalação das dependências necessárias para lidar com aceleração de GPU e tensores de imagem/texto.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# import os, importlib.util
# 
# # Instalação e atualização dos pacotes essenciais para processamento paralelo e fine-tuning
# !pip install --upgrade -qqq uv
# !uv pip install -qqq "torch==2.8.0" "triton>=3.3.0" torchvision bitsandbytes xformers==0.0.32.post2
# !uv pip install -qqq "unsloth_zoo[base] @ git+https://github.com/unslothai/unsloth-zoo" "unsloth[base] @ git+https://github.com/unslothai/unsloth"
# !uv pip install -qqq --no-deps "torchcodec==0.7.0"
# !uv pip install --upgrade --no-deps "tokenizers>=0.22.0,<=0.23.0" trl==0.22.2
# !uv pip install transformers==5.2.0 flash-linear-attention causal_conv1d==1.6.0
# !uv pip install --no-deps --upgrade "torchao>=0.16.0"

"""## 2. Inicialização do Modelo Multimodal
Carregamento do modelo e do tokenizador associado. O recurso `use_gradient_checkpointing` será ativado para economizar memória ao lidar com tokens de imagens.
"""

from unsloth import FastVisionModel
import torch

model_id = "unsloth/Qwen3.5-0.8B"

model, tokenizer = FastVisionModel.from_pretrained(
    model_id,
    load_in_4bit = False,
    use_gradient_checkpointing = "unsloth",
)

"""## 3. Parametrização PEFT (Parameter-Efficient Fine-Tuning)
Ajuste da rede inserindo as matrizes de rank baixo (LoRA). Decidi congelar parte da rede e habilitar o treinamento apenas em camadas de visão, linguagem, atenção e perceptron multicamadas (MLP), usando um rank (r) de 16 para balancear generalização e viabilidade computacional.
"""

model = FastVisionModel.get_peft_model(
    model,
    finetune_vision_layers     = True,
    finetune_language_layers   = True,
    finetune_attention_modules = True,
    finetune_mlp_modules       = True,

    r = 16,           # Rank da matriz LoRA
    lora_alpha = 16,  # Fator de escala do LoRA
    lora_dropout = 0,
    bias = "none",
    random_state = 42, # Semente padronizada para reprodutibilidade
    use_rslora = False,
    loftq_config = None,
)

"""## 4. Pipeline de Preprocessamento do Dataset
Para a tarefa de instrução supervisionada, o formato ideal é transformar as anotações do dataset em um diálogo assistido. Aqui, defino o prompt primário ("Escreva a representação em LaTeX para esta imagem.").
"""

from datasets import load_dataset

# Base de dados OCR contendo pares (imagem_equação, codigo_latex)
dataset = load_dataset("unsloth/LaTeX_OCR", split="train")

prompt_instrucao = "Escreva a representação em LaTeX para esta imagem."

def preparar_dataset_conversacional(amostra):
    dialogo = [
        { "role": "user",
          "content" : [
            {"type" : "text",  "text"  : prompt_instrucao},
            {"type" : "image", "image" : amostra["image"]} ]
        },
        { "role" : "assistant",
          "content" : [
            {"type" : "text",  "text"  : amostra["text"]} ]
        },
    ]
    return { "messages" : dialogo }

dataset_treino_estruturado = [preparar_dataset_conversacional(amostra) for amostra in dataset]

"""## 5. Loop de Treinamento e Otimização
Configuração dos hiperparâmetros (Learning Rate, batching e estratégias de decaimento de pesos) utilizando `SFTTrainer`.
"""

from unsloth.trainer import UnslothVisionDataCollator
from trl import SFTTrainer, SFTConfig

# Colocando a arquitetura em modo de treino
FastVisionModel.for_training(model)

config_treino = SFTConfig(
    per_device_train_batch_size = 2,
    gradient_accumulation_steps = 4,
    warmup_steps = 5,
    max_steps = 60, # Ajustável dependendo do tempo de execução disponível
    learning_rate = 2e-4,
    logging_steps = 10,
    optim = "adamw_8bit", # Otimizador em 8 bits para eficiência
    weight_decay = 0.001,
    lr_scheduler_type = "linear",
    seed = 42,
    output_dir = "pesos_treinamento",
    report_to = "none",
    remove_unused_columns = False,
    dataset_text_field = "",
    dataset_kwargs = {"skip_prepare_dataset": True},
    max_length = 2048,
)

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    data_collator = UnslothVisionDataCollator(model, tokenizer),
    train_dataset = dataset_treino_estruturado,
    args = config_treino,
)

# Executa o Fine-Tuning
metricas_treino = trainer.train()

"""## 6. Validação do Modelo (Inferência)
Teste empírico para analisar como o modelo reage após a alteração dos pesos utilizando o conjunto de amostras com uma imagem não exposta ao fluxo imediato de épocas.
"""

# Comutando para o modo de inferência para otimizar velocidade e memória
FastVisionModel.for_inference(model)

# Pegando uma imagem aleatória de teste da base
imagem_teste = dataset[5]["image"]

mensagens = [
    {"role": "user", "content": [
        {"type": "image"},
        {"type": "text", "text": prompt_instrucao}
    ]}
]

texto_entrada = tokenizer.apply_chat_template(mensagens, add_generation_prompt=True)
inputs = tokenizer(
    imagem_teste,
    texto_entrada,
    add_special_tokens = False,
    return_tensors = "pt",
).to("cuda")

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer, skip_prompt = True)

print("Gerando a equação LaTeX baseada na imagem...")
saida_gerada = model.generate(
    **inputs,
    streamer = text_streamer,
    max_new_tokens = 128,
    use_cache = True,
    temperature = 0.5,
    min_p = 0.1
)

"""## 7. Persistência dos Resultados
Salvando os tensores LoRA localmente. Esses adaptadores podem ser carregados no futuro junto ao modelo base para recuperar as capacidades aprendidas sem a necessidade de re-treinamento.
"""

diretorio_modelo = "meu_modelo_latex_ocr"

model.save_pretrained(diretorio_modelo)
tokenizer.save_pretrained(diretorio_modelo)
print(f"Adaptadores salvos com sucesso em: {diretorio_modelo}")